- name: Markets
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

        - type: rss
          limit: 10
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://www.ft.com/technology?format=rss
              title: Financial Times
            - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
              title: Wall Street Journal

    - size: full
      widgets:
#        - type: group
#          widgets:
#            - type: hacker-news

        - type: videos
          style: grid-cards
          channels:
            - UCvSXMi2LebwJEM1s4bz5IBA # New Money
            - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
            - UCAl9Ld79qaZxp9JzEOwd3aA # Bankless

    - size: small
      widgets:
        - type: weather
          location: Harlow, United Kingdom
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          hide-location: true

        - type: markets
          title: Indices
          markets:
            - symbol: SPY
              name: S&P 500
            - symbol: DX-Y.NYB
              name:
                Dollar Index

        - type: markets
          title: Ccrypto
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum
            - symbol: UPXI
              name: UPXI
            - symbol: SBET
              name: SBET

        - type: markets
          title: Stocks
          sort-by: absolute-change
          markets:
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: MSFT
              name: Microsoft
            - symbol: GOOGL
              name: Google
            - symbol: AMD
              name: AMD
            - symbol: AMZN
              name: Amazon
            - symbol: INTC
              name: Intel

        - type: releases
          cache: 1d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          token: ${GITHUB_TOKEN}
          repositories:
            - NethermindEth/nethermind
            - ethereum/go-ethereum
            - sigp/lighthouse
            - ava-labs/avalanchego
            - amir20/dozzle
            - funfair-tech/funfair-docker-bsc-client-builder